# Generated by Django 4.1 on 2023-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=22)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=22)),
                ('signuptime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
